### ISSUE TITLE
fix internal links to api-doc paths

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.com-old#2]
Travis reports these incorrect links:

- ./_site/knowledge-base/freme-for-api-users/authentication.html

  *  linking to /api-doc/full.html#User_delete_user_username, but User_delete_user_username does not exist (line 660)

  *  linking to /api-doc/full.html#User_post_authenticate, but User_post_authenticate does not exist (line 624)

  *  linking to /api-doc/full.html#User_post_user, but User_post_user does not exist (line 616)

  *  linking to /api-doc/full.html#User_put_user_username, but User_put_user_username does not exist (line 651)

  *  linking to /api-doc/full.html#resource_User, but resource_User does not exist (line 612)

- ./_site/knowledge-base/freme-for-api-users/filtering.html

  *  linking to /api-doc/full.html#resource_General_Information, but resource_General_Information does not exist (line 854)

- ./_site/knowledge-base/freme-for-api-users/freme-ner.html

  *  linking to /api-doc/full.html#e-Entity_executeFremeNer, but e-Entity_executeFremeNer does not exist (line 730)

- ./_site/knowledge-base/freme-for-api-users/xslt-transformation.html

  *  linking to /api-doc/full.html#Pipelining_post_pipelining_templates, but Pipelining_post_pipelining_templates does not exist (line 785)

  *  linking to /api-doc/full.html#resource_Toolbox/XSLT-Converter, but resource_Toolbox/XSLT-Converter does not exist (line 641)

  *  linking to /api-doc/full.html#resource_Toolbox/XSLT-Converter, but resource_Toolbox/XSLT-Converter does not exist (line 789)

- ./_site/tutorials/entity-recognition-against-custom-dataset.html

  *  linking to /api-doc/full.html#e-Entity_createDataset, but e-Entity_createDataset does not exist (line 863)

- ./_site/tutorials/getting-started-with-e-link.html

  *  linking to /api-doc/full.html#User_post_authenticate, but User_post_authenticate does not exist (line 896)

  *  linking to /api-doc/full.html#User_post_authenticate, but User_post_authenticate does not exist (line 923)

  *  linking to /api-doc/full.html#User_post_authenticate, but User_post_authenticate does not exist (line 948)

- ./_site/tutorials/html-to-epub.html

  *  linking to /api-doc/full.html#resource_e-Publishing, but resource_e-Publishing does not exist (line 569)

  *  linking to /api-doc/full.html#resource_e-Publishing, but resource_e-Publishing does not exist (line 585)

**Comment by jnehring** [comment]
When you fix the links, please take care that the URLs relative from the homepage stay the same. This is important because URLs should be permanent.

**Comment by jnehring** [comment]
This problem occurs in firefox only, in google chrome it works.

**Comment by ArneBinder** [comment]
ToDo: fix disable link anchor checks when using html-proofer with travis

**Comment by ArneBinder** [comment]
Done.
