### ISSUE TITLE
setup dev docu

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-project.github.com-old#3]
The content of the gh-pages branch should provide as dev version of the documentation. At the moment the content of the gh-pages branch clashes with the master branch content, if the repo name follows the gh-pages naming conventions for organization pages, i.d. it has to be `<organization>.github.io`.

**Comment by jnehring** [comment]
So we will use Jenkins to build the dev version and GitHub to build the master version. Please try out this workflow.

**Comment by ArneBinder** [comment]
@jnehring Implemented, [see](http://api-dev.freme-project.eu/doc-temp/index.html).  
Furthermore, jenkins adds the jekyll variable `basePath: /temp-doc` to the `_config.yml`, so there is nowthing to do when merging the `dev` branch into the `master` except changing the api configuration. All freme api urls used (and mentioned) in the documentation (including the interactive swagger doc) will be set via the jekyll `_config.yml`. This is the [current `dev` setting](https://github.com/freme-project/freme-project.github.com/blob/dev/_config.yml#L8-L12):

```
apiProtocol: https
apiHost: api-dev.freme-project.eu
apiBasePath: /current
```
